
<?php echo $this->before_tabular_output(); ?>

    <thead>
        <tr>
            <th scope="col" class="qm-sorted-asc qm-sortable-column" role="columnheader" aria-sort="ascending">
                <?php echo $this->build_sorter('#'); ?>
            </th>
            <th scope="col" class="qm-filterable-column">
                <?php echo $this->build_filter('type', $data['types'], 'Command'); ?>
            </th>
            <th scope="col">
                Caller
            </th>
            <th scope="col" class="qm-num qm-sortable-column" role="columnheader" aria-sort="none">
                <?php echo $this->build_sorter('Time (ms)'); ?>
            </th>
        </tr>
    </thead>

    <tbody>

        <?php foreach ($data['commands'] as $no => $command) : ?>
            <tr
                data-qm-type="<?php echo strtoupper($command['command']); ?>"
                data-qm-time="<?php echo strtoupper($command['time']); ?>"
            >
                <th scope="row" class="qm-row-num qm-num">
                    <?php echo $no + 1; ?>
                </th>

                <td class="qm-row-sql qm-ltr qm-wrap">
                    <code>
                        <b><?php echo strtoupper($command['command']); ?></b>
                        <?php echo esc_html(implode(' ', $command['parameters'])); ?>
                    </code>
                </td>

                <td class="qm-row-caller qm-ltr qm-has-toggle qm-nowrap">
                    <?php if (is_array($command['backtrace'])) : ?>
                        <ul>
                            <?php foreach ($command['backtrace'] as $trace) : ?>
                                <li>
                                    <code><?php echo esc_html($trace); ?></code>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php else : ?>
                        <?php echo self::build_toggler(); ?>

                        <?php $caller = $command['backtrace']->get_caller(); ?>
                        <?php $trace = $command['backtrace']->get_display_trace(); ?>
                        <?php array_shift($trace); ?>

                        <ol>
                            <li>
                                <?php echo self::output_filename($caller['display'], $caller['calling_file'], $caller['calling_line']); ?>
                            </li>
                            <div class="qm-toggled">
                                <?php foreach ($trace as $item) : ?>
                                    <li>
                                        <?php echo self::output_filename($item['display'], $item['calling_file'], $item['calling_line']); ?>
                                    </li>
                                <?php endforeach; ?>
                            </div>
                        </ol>
                    <?php endif; ?>
                </td>

                <td class="qm-num qm-row-time" data-qm-sort-weight="<?php echo $command['time']; ?>">
                    <code><?php echo number_format_i18n($command['time'], 4); ?></code>
                </td>
            </tr>
        <?php endforeach; ?>

    </tbody>

    <tfoot>

        <tr>
            <td colspan="3">
                Total:
                <span class="qm-items-number">
                    <?php echo number_format_i18n(count($data['commands'])); ?>
                </span>
            </td>

            <td class="qm-num qm-items-time">
                <?php echo number_format_i18n(array_sum(array_column($data['commands'], 'time'))); ?>
            </td>
        </tr>

    </tfoot>

<?php echo $this->after_tabular_output(); ?>
