<?php

$license = $this->license();

$diagnostics = $this->diagnostics();

$status = $diagnostics['general']['status']->html;
$dropin = $diagnostics['general']['dropin']->html;
$evictionPolicy = $diagnostics['general']['eviction-policy'];
$memory = $diagnostics['statistics']['memory'];

$configError = $this->config->initException ?? false;
$configDefined = defined('\WP_REDIS_CONFIG');
$isDisabled = $diagnostics->isDisabled();
$dropinExists = $diagnostics->dropinExists();
$dropinIsValid = $dropinExists && $diagnostics->dropinIsValid();
$dropinIsUpToDate = $dropinExists && $diagnostics->dropinIsUpToDate();
$fileModsAllowed = wp_is_file_mod_allowed('object_cache_dropin');

$admin_url = function ($path) {
    $callback = is_network_admin() ? 'network_admin_url' : 'admin_url';

    return $callback($path);
};

?>

<div class="rcp:widget">

    <ul>
        <li>
            <span class="dashicons dashicons-cloud"></span>
            Status: <?php echo $status; ?>
        </li>

        <li>
            <span class="dashicons dashicons-admin-plugins"></span>
            Drop-in: <?php echo $dropin; ?>
        </li>

        <?php if (! $license->isValid()) : ?>
            <li>
                <span class="dashicons dashicons-admin-network"></span>
                License:
                <data class="error">
                    <?php if (! $this->token()) : ?>
                        Missing token
                    <?php else : ?>
                        <?php echo ucwords($license->state() ?? 'error'); ?>
                    <?php endif; ?>
                </data>
            </li>
        <?php endif; ?>

        <?php if ($evictionPolicy->value) : ?>
            <li>
                <span class="dashicons dashicons-screenoptions"></span>
                Eviction Policy: <?php echo $evictionPolicy->html; ?>
            </li>
        <?php endif; ?>

        <?php if ($memory->value && (! is_multisite() || is_network_admin())) : ?>
            <li>
                <span class="dashicons dashicons-screenoptions"></span>
                Memory: <?php echo $memory->html; ?>
            </li>
        <?php endif; ?>
    </ul>

    <div class="actions">

        <?php if (! $isDisabled && $dropinExists && $dropinIsValid && $diagnostics->ping()) : ?>
            <a class="button button-primary"
                onclick="return confirm('Are you sure you want to flush the object cache?')"
                href="<?php echo wp_nonce_url($admin_url(add_query_arg('rediscache-action', 'flush-cache', 'index.php')), 'flush-cache'); ?>"
            >
                Flush Object Cache
            </a>
        <?php endif; ?>

        <?php if ($fileModsAllowed && (! is_multisite() || is_network_admin())) : ?>

            <?php if (! $dropinExists || ! $dropinIsValid) : ?>
                <?php if ($configDefined) : ?>
                    <a class="button button-primary"
                        onclick="return confirm('Installing the object cache might log you out. After logging back in, be sure to flush the object cache once to avoid stale data.')"
                        href="<?php echo wp_nonce_url($admin_url(add_query_arg('rediscache-action', 'enable-dropin', 'index.php')), 'enable-dropin'); ?>"
                    >
                        Enable Object Cache
                    </a>
                <?php else : ?>
                    <a class="button button-primary" href="#!" disabled>
                        Enable Object Cache
                    </a>
                <?php endif; ?>
            <?php elseif ($dropinIsValid && ! $dropinIsUpToDate) : ?>
                <a class="button button-secondary"
                    href="<?php echo wp_nonce_url($admin_url(add_query_arg('rediscache-action', 'update-dropin', 'index.php')), 'update-dropin'); ?>"
                >
                    Update Drop-in
                </a>
            <?php endif; ?>

            <?php if ($dropinExists && $dropinIsValid && ! $isDisabled) : ?>
                <a class="button button-secondary button-ml-auto"
                    onclick="return confirm('Are you sure you want to disable the object cache?')"
                    href="<?php echo wp_nonce_url($admin_url(add_query_arg('rediscache-action', 'disable-dropin', 'index.php')), 'disable-dropin'); ?>"
                >
                    Disable
                </a>
            <?php endif; ?>

        <?php endif; ?>

    </div>

</div>

<?php if ($isDisabled) : ?>

    <div class="rcp:widget-sub">

        <?php if ($diagnostics->isDisabledUsingConstant()) : ?>

            <p>
                The object cache is disabled using the <code>WP_REDIS_DISABLED</code> constant.
            </p>

        <?php elseif ($diagnostics->isDisabledUsingEnvVar()) : ?>

            <p>
                The object cache is currently disabled using the <code>WP_REDIS_DISABLED</code> environment variable.
            </p>

        <?php endif; ?>

    </div>

<?php elseif (! $configDefined) : ?>

    <div class="rcp:widget-sub">
        <p>
            To enable the object cache, set up the <code>WP_REDIS_CONFIG</code> constant.
        </p>
    </div>

<?php elseif ($configError) : ?>

    <div class="rcp:widget-sub">
        <p>
            An error occurred during the instantiation of the configuration:
        </p>
        <ul>
            <li><code><?php echo esc_html($configError->getMessage()); ?></code></li>
        </ul>
    </div>

<?php elseif (! empty($wp_object_cache_errors)) : ?>

    <div class="rcp:widget-sub">

        <p>
            <?php if (count($wp_object_cache_errors) > 1) : ?>
                <?php echo count($wp_object_cache_errors); ?> object cache errors have occurred:
            <?php else : ?>
                An object cache error has occurred:
            <?php endif; ?>
        </p>

        <ul>
            <?php foreach (array_slice($wp_object_cache_errors, 0, 3) as $error) : ?>
                <li><code><?php echo esc_html($error); ?></code></li>
            <?php endforeach; ?>
        </ul>

    </div>

<?php elseif (! $this->token()) : ?>

    <div class="rcp:widget-sub">
        <p>
            Automatic updates for Object Cache Pro are disabled, because no license token is set.
        </p>
    </div>

<?php elseif (! $license->isValid()) : ?>

    <div class="rcp:widget-sub">
        <p>
            Automatic updates for Object Cache Pro are disabled, because the license token is not valid.
        </p>
    </div>

<?php endif; ?>
